### ISSUE TITLE
More distinct color selection for edges

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#2]
I think we should choose more distinct colors for edges since some are real close (e.g. controls state change of and controls transport of). There should be online tools for doing this.

**Comment by ugurdogrusoz** [comment]
It is a lot better now but still some are very close such as:
- catalysis precedes and controls transport of chemical
- used to produce and controls phosphorylation of

**Comment by metincansiper** [comment]
I updated the colors used for that one the following image contains all 4 of the mentioned edges: 
<img width="417" alt="screen shot 2019-03-01 at 10 26 53 am" src="https://user-images.githubusercontent.com/6534865/53658242-14a35280-3c0d-11e9-9b5d-890b13891b8d.png">
