### ISSUE TITLE
Add Legend for SIF

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#5]
After #2 is done and finalized, we should create a Legend and add under the Legend menu as "SIF". I have the sources for this I can help.

**Comment by metincansiper** [comment]
Here is the SIF edge color map: https://github.com/metincansiper/sbgnviz.js/blob/sif-support/src/utilities/element-utilities-factory.js#L2227

**Comment by ugurdogrusoz** [comment]
@metincansiper I am emailing you the legend file. Please check and use it if correct.

**Comment by metincansiper** [comment]
Thanks @ugurdogrusoz. I named the related menu item as "Simple Interaction Format" and the following is how the legend looks like in Newt:

<img width="1440" alt="screen shot 2019-03-04 at 10 45 56 am" src="https://user-images.githubusercontent.com/6534865/53755409-52051b80-3e6b-11e9-9189-ff780ffd4d60.png">

**Comment by ugurdogrusoz** [comment]
@ozgunbabur can you check the legend (screenshot above) for correctness (direction and name of edges) as well?
@metincansiper can you deploy the latest so I can check the legend at work?

**Comment by metincansiper** [comment]
@ugurdogrusoz sorry I forgot to do this. I just have deployed the latest.

**Comment by ugurdogrusoz** [comment]
The legend is too small. In fact, we should make sure it's displayed in original size.
I would also name the menu item as "SIF" (instead of "Simple Interaction Format"). Let's leave the legend title long though.

**Comment by metincansiper** [comment]
@ugurdogrusoz it was not being displayed in the original size but nothing changed when I displayed it by the original size. Most probably the adjusted size was already the same of the original. If you wish I can set a bigger size or just make it using the original size. BTW the same is true for AF and SIF too, they also use an adjusted size. I can make them using the original size if you wish.

**Comment by ugurdogrusoz** [comment]
Let's just increase its size and make it more readable and compatible with other legends. A macromolecule should look the same size in all legends for instance.

**Comment by metincansiper** [comment]
@ugurdogrusoz how does this one look?

<img width="1440" alt="Screen Shot 2019-03-13 at 9 53 32 PM" src="https://user-images.githubusercontent.com/6534865/54332241-83ec4f80-45da-11e9-8b0a-30136c5b090a.png">

The following is the AF view, in screen they look more readable I attach images so that you can compare the sizes.

<img width="1440" alt="Screen Shot 2019-03-13 at 9 55 25 PM" src="https://user-images.githubusercontent.com/6534865/54332288-beee8300-45da-11e9-956e-afd0d3fbcafd.png">

**Comment by ugurdogrusoz** [comment]
Yes, looks good, thanks. Let me know when it's deployed so I can verify and close the issue.

**Comment by metincansiper** [comment]
I deployed it.
