### ISSUE TITLE
Infobox tooltips

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#6]
I think it would be better if tooltips for infoboxes were shown on mouse over instead of selection followed by left click on the box. Current way of showing these values might also result in unintentionally moving the nodes.

@metincansiper please remind me if the same mechanism can be used for PD and AF if desired, for instance to show the whole label when truncated?

**Comment by metincansiper** [comment]
For now I am not sure if showing them directly on mouseover would affect the performance, but I suspect it may. How about putting a little bit of waiting time before showing the tooltips on mouseover?

**Comment by ugurdogrusoz** [comment]
A little delay makes sense I think
