### ISSUE TITLE
File menu changes

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#7]
I suggest we re-do the file menu as in [here](https://docs.google.com/spreadsheets/d/1g-qPl9iFqg4AWfGzCTwNJ5GwhqCmrjWrx_FlYWDANqc/edit?usp=sharing). Let me know when it's functional so I can test.

**Comment by metincansiper** [comment]
>  SIF Format: "SIF Rich" or something along those lines perhaps. I guess this is SIF with style information.

No, actually this file only contains the style data. It is not a rich form of SIF file. The style content from the file is applied to the existing SIF graph (one of the columns is reserved for selector of sif elements to apply the style from the related line).

@ugurdogrusoz  What name do you think would be good in this case?

**Comment by metincansiper** [comment]
>  SIF Layout: Is this SIF file with layout info?

It is a mapping of position per SIF node. It has the following columns: name, posX, posY

**Comment by metincansiper** [comment]
>  Current:  SBGN-ML 0.3   New: SBGN-ML Plain 0.3 Same as "SBGN-ML Plain" except version is 0.3

What I understand from [this line](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/json-to-sbgnml-converter-factory.js#L70) from sbgnviz is that "plain" is one of the version options. Therefore, something like "Plain 0.3" does not look possible for the current structure. I do not know the reason why "plain" is one of the type options. However, I can change it if you think it is safe to do so.

**Comment by ugurdogrusoz** [comment]
> > SIF Format: "SIF Rich" or something along those lines perhaps. I guess this is SIF with style information.
> 
> No, actually this file only contains the style data. It is not a rich form of SIF file. The style content from the file is applied to the existing SIF graph (one of the columns is reserved for selector of sif elements to apply the style from the related line).
> 
> @ugurdogrusoz What name do you think would be good in this case?

How about "SIF Style"?

**Comment by ugurdogrusoz** [comment]
> > Current:  SBGN-ML 0.3   New: SBGN-ML Plain 0.3 Same as "SBGN-ML Plain" except version is 0.3
> 
> What I understand from [this line](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/json-to-sbgnml-converter-factory.js#L70) from sbgnviz is that "plain" is one of the version options. Therefore, something like "Plain 0.3" does not look possible for the current structure. I do not know the reason why "plain" is one of the type options. However, I can change it if you think it is safe to do so.

Let's forget about / delete SBGN-ML Plain 0.3 then

**Comment by ugurdogrusoz** [comment]
Discussed and necessary changes were made in original Google sheet

**Comment by ugurdogrusoz** [comment]
Import > SIF File should be Import > SIF
