### ISSUE TITLE
Naming of SIF edges

### ISSUE THREAD

**Issue by ugurdogrusoz** [metincansiper/newt#8]
@ozgunbabur @metincansiper Would you consider making these changes in naming SIF edges for *consistency* with others? I noticed these while preparing the legend:
- downregulates-expression -> downregulates-expression-of
- upgregulates-expression -> upregulates-expression-of
- controls-transport-of-chemical -> controls-transport-of
- chemical-affects -> affects

**Comment by ozgunbabur** [comment]
These names are coming from other projects that produce these. It is better
if we use the same name.
